### ISSUE TITLE
Error while import pet api

### ISSUE THREAD

**Issue by ItsReddi** [cebe/yii2-openapi#2]
Based on: https://app.swaggerhub.com/apiproxy/schema/file/apis/ItsReddi/Petstore/1.0.0?format=yaml

Could be a php-openapi issue.

Generation will fail with the following error:
```
Running 'REST API Generator'...

array (
  0 => 'placed',
  1 => 'approved',
  2 => 'delivered',
)Exception 'cebe\openapi\exceptions\UnknownPropertyException' with message 'Getting unknown property: cebe\openapi\spec\Schema::required'

in /var/www/html/vendor/cebe/php-openapi/src/SpecBaseObject.php:317

Stack trace:
#0 /var/www/html/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(645): cebe\openapi\SpecBaseObject->__get('required')
#1 /var/www/html/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(890): cebe\yii2openapi\generator\ApiGenerator->generateModels()
#2 /var/www/html/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(53): cebe\yii2openapi\generator\ApiGenerator->generate()
#3 /var/www/html/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(36): yii\gii\console\GenerateAction->generateCode()
#4 [internal function]: yii\gii\console\GenerateAction->run()
#5 /var/www/html/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#7 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('api', Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('api', Array)
#9 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gii/api', Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('gii/api', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /var/www/html/yii(9): yii\base\Application->run()
#13 {main}
```

**Comment by cebe** [comment]
> Could be a php-openapi issue.

it is: https://github.com/cebe/php-openapi/issues/36

**Comment by cebe** [comment]
added a workaround in 10cdb8b

**Comment by cebe** [comment]
https://github.com/cebe/php-openapi/issues/36 is now fixed.
