### ISSUE TITLE
problem in ApiGenarator while generating models from OpenApi 3 yaml

### ISSUE THREAD

**Issue by geokal** [cebe/yii2-openapi#68]
Hi the example wit the petstore yaml works great, but with my huge yaml , the genrator struggles. I know fixing the yaml is the right way to go. 

Versions details:
```
yii
2.0.42.1

PHP 7.3.28 (cli) (built: May 12 2021 13:40:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies
```
composer.json

```
{
    "name": "cebe/yii2-app-api",
    "description": "Yii Framework Application Template for quickly building API-first applications.",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=7.1.0",
        "yiisoft/yii2": "~2.0.16",
        "cebe/php-openapi": "^1.1",
        "cebe/yii2-openapi": "^1.0",
        "yiisoft/yii2-gii": "~2.1.0"
    },
    "autoload": {
        "psr-4": {
            "api\\": "api/",
            "backend\\": "backend/",
            "console\\": "console/",
            "common\\": "common/"
        }
    },
    "config": {
        "platform": {"php": "7.1.3"},
        "fxp-asset": {
            "enabled": false
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```

So the error is the following:
```
array ( 0 => 'DISABLED', 1 => 'ENABLED', )array ( 0 => 'DISABLED', 1 => 'ENABLED', )
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php on line 697. in /app/vendor/yiisoft/yii2/web/Response.php:373
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(346): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#4 {main}
Previous exception:
yii\base\ErrorException: Invalid argument supplied for foreach() in /app/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php:645
Stack trace:
#0 /app/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(645): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/app/vendor/ceb...', 645, Array)
#1 /app/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(890): cebe\yii2openapi\generator\ApiGenerator->generateModels()
#2 /app/vendor/yiisoft/yii2-gii/src/controllers/DefaultController.php(61): cebe\yii2openapi\generator\ApiGenerator->generate()
#3 [internal function]: yii\gii\controllers\DefaultController->actionView('api')
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('view', Array)
#7 /app/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('gii/default/vie...', Array)
#8 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 /app/backend/web/index.php(8): yii\base\Application->run()
#10 {main}
```

And OpenApi part that seems wrong is:

```    AppPkgInfoModifications:
      description: >-
        'The data type represents the operational state for an application package resource'
      type: object
      required:
        - operationState
      properties:
        operationState:
          type: string
          enum:
            - DISABLED
            - ENABLED
    AppSoftwareVersion:
      description: >-
        Software version of the application. This is updated when there is any change to the software in the onboarded application package.
      type: string
    AppPkg.OperationalState:
      description: >-
        Operational state of the onboarded application package: ENABLED: the application package can be used for instantiation of new application instances. DISABLED: the application package cannot be used for further application instantiation requests.
      type: string
      enum:
        - ENABLED
        - DISABLED
```

Inside dockers copy of the yii2-openapi --> ApiGenerator.php : (645) points to the following piece of code:

In ```protected function generateModels()```
```
645 foreach ($schema->required as $property) {
646                 if (!isset($attributes[$property])) {
647                     continue;
648                 }
649                 $attributes[$property]['required'] = true;
650             }
```
Any tips on how to tackle this one? Should I upgrade both yii and other deps?
Thanks in advance!!!

**Comment by synatree** [comment]
I just added `?? []` to the foreach loop you posted... solved that part of the problem.
