### ISSUE TITLE
Parsing fails when object item contains a $ref

### ISSUE THREAD

**Issue by davidnewcomb** [cebe/yii2-openapi#91]
This works:

```
info:
  version: 1.0.0
  title: Bad reference type handling
servers:
  - url: http://localhost:3001/api/v4
tags:
  - name: watching
    #description: Operations about watching people
openapi: 3.0.2
paths:
  "/watch/{personId}":
    post:
      operationId: toggleWatch
      summary: "Toggle person watch"
      ##description: ""
      tags:
        - watching
      parameters:
        - name: personId
          schema:
            $ref: "#/components/schemas/Mid"
          in: path
          required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonWatch"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonWatch"
components:
  schemas:
    Mid:
      type: string
      #description: The MongoDB Identifier
      #pattern: ^[0-9a-f]{24}$
    PersonWatch:
      description: Information about a user watching a Person
      type: object
      properties:
        personId:
          #$ref: "#/components/schemas/Mid"
          type: string
        userId:
          #$ref: "#/components/schemas/Mid"
          type: string
```
But if you change it to:
```
    PersonWatch:
      description: Information about a user watching a Person
      type: object
      properties:
        personId:
          $ref: "#/components/schemas/Mid"
          #type: string
        userId:
          $ref: "#/components/schemas/Mid"
          #type: string
```

Then you get:
```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: description'

in /backend-php/vendor/cebe/yii2-openapi/src/lib/AttributeResolver.php:204

Stack trace:
#0 /backend-php/vendor/cebe/yii2-openapi/src/lib/AttributeResolver.php(204): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/davidnew...', 204, Array)
#1 /backend-php/vendor/cebe/yii2-openapi/src/lib/AttributeResolver.php(107): cebe\yii2openapi\lib\AttributeResolver->resolveProperty('personId', Object(cebe\openapi\spec\Reference), false)
#2 /backend-php/vendor/cebe/yii2-openapi/src/lib/SchemaToDatabase.php(103): cebe\yii2openapi\lib\AttributeResolver->resolve()
#3 /backend-php/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(731): cebe\yii2openapi\lib\SchemaToDatabase->generateModels(Object(cebe\openapi\spec\OpenApi))
#4 /backend-php/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(522): cebe\yii2openapi\generator\ApiGenerator->prepareModels()
#5 /backend-php/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(408): cebe\yii2openapi\generator\ApiGenerator->generateModels()
#6 /backend-php/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(53): cebe\yii2openapi\generator\ApiGenerator->generate()
#7 /backend-php/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(36): yii\gii\console\GenerateAction->generateCode()
#8 [internal function]: yii\gii\console\GenerateAction->run()
#9 /backend-php/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#10 /backend-php/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Action->runWithParams(Array)
#11 /backend-php/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('api', Array)
#12 /backend-php/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('api', Array)
#13 /backend-php/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('gii/api', Array)
#14 /backend-php/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('gii/api', Array)
#15 /backend-php/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /backend-php/yii(9): yii\base\Application->run()
#17 {main}
19:41:56 /backend-php 551 (master) $ 
```
Some of the line numbers may not be correct because my version is filled with debug to figure out why it is not working. It should still not work for you but with correct line numbers!

According to https://swagger.io/specification/#schema-object  (search for 'Simple Model') it should be possible.

**Comment by davidnewcomb** [comment]
This works, so it might be a problem with the php-openapi parser. I think "/'/no-quotes is suppose to work as quotes for strings.

```
    PersonWatch:
      description: Information about a user watching a Person
      type: object
      properties:
        personId:
          $ref: #/components/schemas/Mid
        userId:
          $ref: #/components/schemas/Mid
```

**Comment by davidnewcomb** [comment]
`Undefined index: description` was a red herring. I think the problem is that you don't support component/schemas which are not objects.

In file: `AttributeResolver::resolveProperty` there is the question, is property a Reference. It checks if it is an object (with /properties/) and if it is then it creates the fields. But if it is not then the program tries to create a table relationship or something. It gets a bit confusing with all the primaryKey stuff that is kind of Off and On at the same time. The implementation breaks down if the property Reference is not an object but a description of a normal field. This is what I wanted:
```
components:
  schemas:
    Mid:
      type: string
      description: The MongoDB Identifier
      pattern: ^[0-9a-f]{24}$
```
It's just a string but the application tries to make it a table.   .....so bug?

**Comment by Insolita** [comment]
Thanks for good example. Will check and fix it asap

**Comment by Insolita** [comment]
Please, use the latest version, the problem should be resolved
